### ISSUE TITLE
Simple Demo

### ISSUE THREAD

**Issue by HartfordSteve** [weepy/jquery.path#1]
It would be great to see a SIMPLE demo. Maybe using a single image or div...

I've been trying to deconstruct your code for about 2 hours now and I, nor any other the people sitting near me, are able to figure out why your code works and ours does not.

**Comment by weepy** [comment]
fair enough i'll add an easy demo :)

**Comment by tripathi-swapnil** [comment]
I am just trying to move a Car in the following path.but i am unable,I am still trying to complete it but don't know why its not working.

**Comment by weepy** [comment]
... what path ?
