### ISSUE TITLE
custom path

### ISSUE THREAD

**Issue by sinanisler** [weepy/jquery.path#16]
how can I draw custom paths?
 like;

start  100,100 , go 200,100 and go 300,100 and finish 400,100.

**Comment by priscillahuang** [comment]
yea is this possible at all? this is exactly what is avail on the YUI lib - http://yuilibrary.com/yui/docs/anim/curve.html

I would assume this is a much-requested feature, are we missing something here?

**Comment by priscillahuang** [comment]
ok managed to get this using beziers - https://github.com/weepy/jquery.path#bezier

the params are pretty similar to the YUI lib concept so pretty easy to get the idea.

**Comment by weepy** [comment]
thanks @priscillahuang
