### ISSUE TITLE
Resume animation

### ISSUE THREAD

**Issue by jarodium** [weepy/jquery.path#23]
I find this is very difficult to resume an arc animation.

Upon resuming the animation, I start the animation from the end angle and stop at the angle I wanted, but, somehow, I get "NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument arg 0 [nsIDOMWindow.getComputedStyle] in", when I request a new animation from the first animation end angle.

Have anyone tried to solve this?

**Comment by weepy** [comment]
this doesn't look like an issue of this library.
