### ISSUE TITLE
Not working in Chrome Version 33.0.1750.154 m (latest version)

### ISSUE THREAD

**Issue by Luen** [weepy/jquery.path#26]
The demo gets an error http://weepy.github.io/jquery.path/

TypeError: Cannot read property 'arc' of undefined
#7 http://weepy.github.io/jquery.path:39:24
#6 http://weepy.github.io/jquery.path/:39:24 Object.path_fns.arc()
#5 http://weepy.github.io/jquery.path/:65:32 HTMLDocument.()
#4 http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js:19:20574 Function.()
#3 http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js:12:7964 Function.o.extend.each()
#2 http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js:19:20541 Function.o.extend.ready()
#1 http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js:19:20855 HTMLDocument.()&host=weepy.github.io

**Comment by weepy** [comment]
fixed
