### ISSUE TITLE
Demos are not working in latest Chrome

### ISSUE THREAD

**Issue by zachwolf** [weepy/jquery.path#28]
I'm not sure if this repo is still being maintained, it looks like the last activity was several years ago.

I'm using Chrome 37.0.2062.124 and getting console errors: `Uncaught TypeError: Cannot read property 'arc' of undefined`

**Comment by nullablemind** [comment]
Correct your site.
It lacks:
1. !DOCTYPE html
2. Tag html and head
3. Quotes from class and id

**Comment by weepy** [comment]
ok so this is fixed. the problem was that github no longer allows exec of
javascript from their raw subdomain. fixed by moving to rawgit service
