### ISSUE TITLE
What is the p parameter in the SineWave function?

### ISSUE THREAD

**Issue by jdmcpeek** [weepy/jquery.path#29]
I think a sine wave animation is very useful, but the documentation doesn't explain clearly what the p parameter is and where it comes from. It is also unclear how to program the beginning and end points of the movement.

**Comment by weepy** [comment]
It's been a while ! --- but I think it's a parameter that changes from 0 to 1 along the path

**Comment by jdmcpeek** [comment]
Wow, I honestly didn't realize you started this project 6 years ago! Thanks for responding. I started writing my own version of this which works pretty well.
