### ISSUE TITLE
problem with IE9

### ISSUE THREAD

**Issue by WaZz2** [weepy/jquery.path#6]
When I go to the demo page(http://weepy.github.com/jquery.path/), IE9 gives an error :
SCRIPT5007: Unable to get value of the property 'arc': object is null or undefined

**Comment by weepy** [comment]
hrm that is odd. unfort I don't have a copy of IE9 to test with !

**Comment by louisremi** [comment]
This is because IE9 doesn't accept to run scripts served with a "text/plain" mime type.
Look at the "Script from https://raw.github.com/... was blocked due to mime type mismatch" error

**Comment by WaZz2** [comment]
Importing the file instead of downloading it fix the error. Thanks
