### ISSUE TITLE
Resetting the direction

### ISSUE THREAD

**Issue by skoch** [weepy/jquery.path#8]
I've created a demo that, upon user initiation, animates objects on a path. When animation is finished, I am reasetting the start and end positions so that upon another click the objects will start at their current position and move the same incement as before around the path.

The problem I'm having, however, is in attempting to reverse the direction. Whereas I can reset the start/end it seems that resetting the 'dir' has no effect on the animation.

Easy fix to be able to reset this parameter?

Thanks.

**Comment by jarodium** [comment]
Hello there
Can you provide the demo or the code here?
